// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfnipvfzbxctvoqluurl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmbmlwdmZ6YnhjdHZvcWx1dXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTU2MDgsImV4cCI6MjA2Nzg5MTYwOH0.EiUebtlcVEPe4VnkUtWqLpLCacPuwu_8CwLtwBkMIC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});